apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
  labels:
    app: headless-test
  name: headless-test
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: headless
  selector:
    app: headless-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: headless-test
  name: headless-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: headless-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: headless-test
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: web
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
