apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  hapee-lb.cfg: |
    # vim set ft=haproxy shiftwidth=2 tabstop=2

    global
      log stderr local1 debug
      stats socket /run/haproxy.sock user hapee-lb group hapee mode 660 level admin expose-fd listeners
      stats timeout 10m
      master-worker

    resolvers kubernetes
      nameserver dns01 10.43.0.10:53
      accepted_payload_size 8192
      resolve_retries 3
      timeout resolve 1s
      timeout retry   1s
      hold other      5s
      hold refused    5s
      hold nx         5s
      hold timeout    5s
      hold valid      1s
      hold obsolete   5s

    defaults
      timeout connect 5s
      timeout client  30s
      timeout server  30s
      mode http
      option redispatch
      retries 3
      timeout http-keep-alive 5s
      # default-server init-addr last,libc,none

    listen stats
      bind :8083
      timeout connect 10s
      timeout client  10s
      timeout server  10s
      stats refresh 5s
      stats uri /
      stats enable

    listen metrics
      bind :8084
      timeout connect 10s
      timeout client  10s
      timeout server  10s
      http-request use-service prometheus-exporter if { path /metrics }


    frontend api_gateway
      bind :8081

      default_backend headless-test

    backend headless-test
      balance leastconn
      option httpchk GET /
      http-check expect status 200
      server-template srv 15 _headless._tcp.headless-test.default.svc.cluster.local:80 resolvers kubernetes resolve-prefer ipv4 check


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy
  name: haproxy
spec:
  type: ClusterIP
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: api
  - port: 8083
    protocol: TCP
    targetPort: 8083
    name: stats
  - port: 8084
    protocol: TCP
    targetPort: 8084
    name: metrics
  selector:
    app: haproxy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - image: test-haproxy
        imagePullPolicy: Never
        name: web
        ports:
        - containerPort: 8081
          protocol: TCP
          name: api
        - containerPort: 8083
          protocol: TCP
          name: stats
        - containerPort: 8084
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: haproxy-config
          mountPath: /etc/hapee-2.2/
      restartPolicy: Always
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
